---
title: "Social Doors ROI to ROI RSA"
author: "Haroon Popal"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    number_sections: true
    toc: true
    toc_float: 
      collapsed: false
    toc_depth: 2
    df_print: paged
    css: !expr here::here("./code/style_srk_behavioral.css")
    knit: (function(inputFile, encoding) { 
      out_dir <- './';
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), out_dir, 'index.html')) })
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)

require("knitr")
opts_knit$set(root.dir = "~/OneDrive - Temple University/olson_lab/projects/social_doors/derivatives/rsa-bw_runs-fb_only/")
```


```{r}
library(ggplot2)
library(dplyr)
library(reshape2)
library(ggpubr)
```




# Set Up

## Import Data
```{r}
roi_sim_region08 <- read.csv(file='roi_region08_similarity.csv', header = TRUE)
roi_sim_region02 <- read.csv(file='roi_region02_similarity.csv', header = TRUE)
roi_sim_striatum <- read.csv(file='roi_striatum_ventral_similarity.csv', header = TRUE)
```


### Combine data
```{r}
roi_roi_sim <- data.frame(colnames=c('subj','group','target','roi','r'))
roi_sim_region08$target <- 'region08'
roi_sim_region02$target <- 'region02'
roi_sim_striatum$target <- 'striatum_ventral'

roi_roi_sim <- rbind(roi_sim_region08,
                     roi_sim_region02,
                     roi_sim_striatum)
```

### Remove autocorrelations
```{r}
roi_roi_sim <- roi_roi_sim[(roi_roi_sim$r != 1), ]

```


## Filter Data

### for ROIs
```{r}
hyp_rois <- c('TPJ_b-social','ATL_b-social','PCC_b-social','AMG_r-social','dmPFC_b-social',
              'vmPFC_b-reward',
              'region08','region02',
              'striatum_ventral')
hyp_rois_names <- c('TPJ','ATL','PCC','AMG (r)',' dmPFC', 'vmPFC',
                    'CB Region 8','CB Region 2',
                    'Ventral Striatum')

roi_roi_sim_roi <- roi_roi_sim[roi_roi_sim$roi %in% hyp_rois, ]

```

## Filter for Task
```{r}
#roi_roi_sim_roi_mdoors <- roi_roi_sim_roi[roi_roi_sim_roi$task %in% 'mdoors', ]
#roi_roi_sim_roi_social <- roi_roi_sim_roi[roi_roi_sim_roi$task %in% 'social', ]

```


# Representational Similarity Analysis

## ANOVA
```{r}
anova_mod <- aov(r ~ target*roi, data=roi_roi_sim_roi)
summary(anova_mod)
```


## One-Sample T-Tests
```{r}
roi_roi_sim_cb8 <- roi_roi_sim_roi[(roi_roi_sim_roi$target == 'region08'), ]
roi_roi_sim_cb2 <- roi_roi_sim_roi[(roi_roi_sim_roi$target == 'region02'), ]
roi_roi_sim_str <- roi_roi_sim_roi[(roi_roi_sim_roi$target == 'striatum_ventral'), ]

```

```{r}
conduct_ttests <- function(raw_df, targ_roi) {
  ttest_df <- data.frame(matrix(ncol=7,nrow=0))
  colnames(ttest_df) <- c('roi','t_stat','p','estimate','CI_l','CI_h','df')
  
  roi_list <- hyp_rois[!hyp_rois %in% targ_roi]
  
  row_n = 1
  for (roi in roi_list) {
    # Filter for ROI data
    roi_data <- raw_df[raw_df$roi %in% roi, ]
    
    # Calculate t-test
    temp_ttest <- t.test(roi_data$r, mu=0)
    
    # Fill in dataframe
    ttest_df[row_n,] <- c(roi,
                          temp_ttest$statistic,
                          temp_ttest$p.value,
                          temp_ttest$estimate, 
                          temp_ttest$conf.int[1],
                          temp_ttest$conf.int[2],
                          temp_ttest$parameter[[1]])
    
    row_n = row_n+1
  }
  
  ttest_df$p_adjust <- p.adjust(ttest_df$p, method='fdr')
  
  return(ttest_df)
}
```


```{r}
all_sim_cb8_rois.ttests <- conduct_ttests(roi_roi_sim_cb8, 'region08')
all_sim_cb2_rois.ttests <- conduct_ttests(roi_roi_sim_cb2, 'region02')
all_sim_str_rois.ttests <- conduct_ttests(roi_roi_sim_str, 'striatum_ventral')

```


## Visualization
```{r}
# Turn ROI column into a factor for sorting during visualization
roi_roi_sim_roi$roi <- factor(roi_roi_sim_roi$roi, levels=hyp_rois)
```


### Bar Graph
```{r}

ggplot(roi_roi_sim_roi, aes(x=roi, y=r, fill=target)) + 
  #stat_summary(fun.data=mean_sdl, geom='bar', position=position_dodge()) + 
  geom_bar(stat = 'summary', position=position_dodge()) +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle=90)) + 
  scale_x_discrete(labels=hyp_rois_names)
```

### Heatmap
```{r}
# Create dataframe for just the ROI to ROI mean correlations
roi_roi_sim_mean <- data.frame()

target_rois <- c('region02','region08','ventral_striatum')
target_rois_stats <- list(all_sim_cb2_rois.ttests, all_sim_cb8_rois.ttests, all_sim_str_rois.ttests)

for (n in 1:length(target_rois)) {
  temp_df <- target_rois_stats[[n]][c('roi','estimate','p_adjust')]
  temp_df$target <- target_rois[n]
  
  roi_roi_sim_mean <- rbind(roi_roi_sim_mean, temp_df)
}

roi_roi_sim_mean$estimate <- as.numeric(roi_roi_sim_mean$estimate)

# Add column for significance symbols
roi_roi_sim_mean$sig_symbol <- ""
roi_roi_sim_mean[roi_roi_sim_mean$p_adjust < .05,]$sig_symbol <- "*"
roi_roi_sim_mean[roi_roi_sim_mean$p_adjust < .01,]$sig_symbol <- "*"
roi_roi_sim_mean[roi_roi_sim_mean$p_adjust < .005,]$sig_symbol <- "***"

# Turn ROI column into a factor for sorting during visualization
roi_roi_sim_mean$roi <- factor(roi_roi_sim_mean$roi, levels=hyp_rois)
roi_roi_sim_mean$target <- factor(roi_roi_sim_mean$target, 
                                  levels=c('region08','region02','striatum_ventral'))
```

```{r}
ggplot(roi_roi_sim_mean, aes(x=roi, y=target, fill=estimate)) +
  geom_tile(width = 1, color = 'grey') + 
  geom_text(aes(label=sig_symbol)) + 
  scale_fill_distiller(palette = "Reds", direction = 1) + 
  theme_minimal() + 
  labs(title = "ROI to ROI Similarity", x = "ROI", y = "Target ROI", fill = "Spearman's rho") + 
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(face="bold", angle = 90, vjust = 0.5),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), plot.background = element_blank()) + 
  scale_x_discrete(labels=hyp_rois_names) + 
  scale_y_discrete(labels=c('CB Region 8', 'CB Region 2', 'Ventral Striatum'))

ggsave('rsa_roi_roi_heatmap.png')
```



